[package]
name = "minigrep"
version = "0.1.0"
authors = ["Abhishek <abhishekshah3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
colored = "2.0.0"
